---
apiVersion: v1
kind: Service
metadata:
  name: grafana-svc 
  labels:
    app: grafana-server
spec:
  selector:
    app: grafana-server
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 32000
    
