---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-storage-pvc
  labels:
    app: grafana-server
spec:
  storageClassName:  nfs-storageclass
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi

