---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-storage-pvc
  labels:
    app: prometheus-server
spec:
  storageClassName:  nfs-storageclass
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 200Mi

