---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc 
  labels:
    app: prometheus-server
spec:
  selector:
    app: prometheus-server
  clusterIP: None
  ports:
  - port: 80
    targetPort: 9090



