---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc 
  labels:
    app: prometheus-server
spec:
  selector:
    app: prometheus-server
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 9090
    nodePort: 31000



